### PR TITLE
Update the README

### PR DESCRIPTION
**Pull request by mlaccetti**
So that the module stuff is happy/working

### CODE REVIEW

**Comment by Ghnuberath** [comment]
Looks like AppVeyor may have gotten gummed up? Let me try rebuilding.

**Comment by mlaccetti** [comment]
Yeah, AppVeyor is not playing nicely. Ugh.

**Comment by Ghnuberath** [comment]
Anything we can do to kick appveyor? Not sure why the branch status isn't being reported.

**Comment by mlaccetti** [comment]
@Ghnuberath appveyor is fuuuuuct - shoot it in the head and just admin merge.  Because goddamn.

**Comment by Ghnuberath** [comment]
It's probably because it's an external branch.

**Comment by mlaccetti** [comment]
Yeah, don't know why I forked the entire repo, could have just done a feature branch here. Derp derp.

**Pull request merged**
